name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and tag backend image
        run: |
          docker build -t habitat-backend:latest -f backend/Dockerfile backend
          docker tag habitat-backend:latest $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/habitat-backend:latest

      - name: Build and tag frontend image
        run: |
          docker build -t habitat-frontend:latest -f frontend/Dockerfile frontend
          docker tag habitat-frontend:latest $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/habitat-frontend:latest

      - name: Push backend image to ECR
        run: |
          docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/habitat-backend:latest

      - name: Push frontend image to ECR
        run: |
          docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/habitat-frontend:latest 